// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gb_prod_api.Data;

#nullable disable

namespace gb_prod_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905132837_AddIsClosedToProductionDay")]
    partial class AddIsClosedToProductionDay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gb_prod_api.Models.ContainerShipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContainerNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ContainerShipments");
                });

            modelBuilder.Entity("gb_prod_api.Models.ContainerShipmentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContainerShipmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("PawGradeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerShipmentId");

                    b.HasIndex("PawGradeId", "ContainerShipmentId")
                        .IsUnique();

                    b.ToTable("ContainerShipmentItems");
                });

            modelBuilder.Entity("gb_prod_api.Models.PawColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PawColors");
                });

            modelBuilder.Entity("gb_prod_api.Models.PawGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PawColorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PawColorId");

                    b.ToTable("PawGrades");
                });

            modelBuilder.Entity("gb_prod_api.Models.ProductionDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("ProductionDays");
                });

            modelBuilder.Entity("gb_prod_api.Models.ProductionRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("MovedOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PawGradeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ProducedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductionDayId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TunnelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionDayId");

                    b.HasIndex("TunnelId");

                    b.HasIndex("PawGradeId", "MovedOutAt");

                    b.ToTable("ProductionRecords");
                });

            modelBuilder.Entity("gb_prod_api.Models.StockAdjustment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PawGradeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityKg")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PawGradeId", "CreatedAt");

                    b.ToTable("StockAdjustments");
                });

            modelBuilder.Entity("gb_prod_api.Models.Tunnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Capacity")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tunnels");
                });

            modelBuilder.Entity("gb_prod_api.Models.ContainerShipmentItem", b =>
                {
                    b.HasOne("gb_prod_api.Models.ContainerShipment", "ContainerShipment")
                        .WithMany("ContainerShipmentItems")
                        .HasForeignKey("ContainerShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gb_prod_api.Models.PawGrade", "PawGrade")
                        .WithMany()
                        .HasForeignKey("PawGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContainerShipment");

                    b.Navigation("PawGrade");
                });

            modelBuilder.Entity("gb_prod_api.Models.PawGrade", b =>
                {
                    b.HasOne("gb_prod_api.Models.PawColor", "PawColor")
                        .WithMany("PawGrades")
                        .HasForeignKey("PawColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PawColor");
                });

            modelBuilder.Entity("gb_prod_api.Models.ProductionRecord", b =>
                {
                    b.HasOne("gb_prod_api.Models.PawGrade", "PawGrade")
                        .WithMany()
                        .HasForeignKey("PawGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gb_prod_api.Models.ProductionDay", "ProductionDay")
                        .WithMany("ProductionRecords")
                        .HasForeignKey("ProductionDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gb_prod_api.Models.Tunnel", "Tunnel")
                        .WithMany()
                        .HasForeignKey("TunnelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PawGrade");

                    b.Navigation("ProductionDay");

                    b.Navigation("Tunnel");
                });

            modelBuilder.Entity("gb_prod_api.Models.StockAdjustment", b =>
                {
                    b.HasOne("gb_prod_api.Models.PawGrade", "PawGrade")
                        .WithMany()
                        .HasForeignKey("PawGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PawGrade");
                });

            modelBuilder.Entity("gb_prod_api.Models.ContainerShipment", b =>
                {
                    b.Navigation("ContainerShipmentItems");
                });

            modelBuilder.Entity("gb_prod_api.Models.PawColor", b =>
                {
                    b.Navigation("PawGrades");
                });

            modelBuilder.Entity("gb_prod_api.Models.ProductionDay", b =>
                {
                    b.Navigation("ProductionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
